### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by cr101** [jackreichert/a-wp-react-redux-theme#1]
Hi Jack,

Thank you for sharing your hard work. Much appreciated.
I am a ReactJS beginner looking for a WP React Theme and I came across your project.

What are the main differences between your theme and [Foxhound](https://github.com/ryelle/Foxhound)?

Does your project currently overcome any of the below [challenges of building a theme as a single page application](https://deliciousbrains.com/creating-a-wordpress-theme-using-the-rest-api-and-vue-js/)?
- Search Engine Optimisation (SEO)
- Client/server code partitioning
- Browser history
- Analytics
- Speed of initial load

**Comment by jackreichert** [comment]
Hi Olivia101,

Thanks for pointing out Foxhound, I hadn't stumbled across it yet. It looks like one main difference is that mine includes Redux as well. Foxhound also is test driven, I did not implement any tests.

- SEO: I have not explored the implications of this yet. The theme does not do server-side rendering in fact it loads all the content after page load. On the other hand, it has browser history and proper url linking so it could go either way. I'll have to check.

- Client/server code partitioning: Not sure what you mean, but a best guess... It's very much partitioned. The client code is responsible for rendering most of the theme, the server code is responsible for serving the initial page and providing the data via the REST API. If you elaborate more about the issue I'd be happy to discuss.

- Browser history: yes.

- Analytics: It does not handle analytics yet. I'll add this to the to dos. It would probably consider every hit as the homepage.

- Speed of initial load: The code compiles pretty small, so there isn't a lot to load. The REST API is also very quick. So you can check it out and see. It's very snappy.
