### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by dirtandrust** [jackreichert/a-wp-react-redux-theme#13]
Steps to reproduce: 

- Install fresh theme, no changes or edits
- Start site locally, home, /reactwpapi/ directory, running MAMP
- Site runs but doesn't load any home content see error below from console:

Unhandled promise rejection 
Error: Request failed with status code 404
Stack trace:
t.exports@http://localhost:8888/reactwpapi/wp-content/themes/a-wp-react-redux-theme-master/bundle.js?ver=20171210:6:29055
t.exports@http://localhost:8888/reactwpapi/wp-content/themes/a-wp-react-redux-theme-master/bundle.js?ver=20171210:28:2905
t.exports/</d[h]@http://localhost:8888/reactwpapi/wp-content/themes/a-wp-react-redux-theme-master/bundle.js?ver=20171210:6:28069

Note: Site does work if I click the home link, not the Home link, and home runs here: http://localhost:8888/

Other pages work, but bundle.js still gets Unhandled promise rejection.

Per my previous bug this theme should be set up to work in any directory, not just / directory, since dev environments often times aren't in the root directory.

**Comment by jackreichert** [comment]
Hi @dirtandrust,
I just pushed a merge that should fix this issue.

**Comment by dirtandrust** [comment]
Excellent I've downloaded the latest build and it's working. Thanks a bunch!
