### ISSUE TITLE
How to run webpack

### ISSUE THREAD

**Issue by Friends-for-Brands** [jackreichert/a-wp-react-redux-theme#2]
Hi Jack,

Thanks for this great Wordpress theme. Looks Awesome! Very curious to build projects using this theme.

One question. How can I run this theme in Webpack?  I have plenty of issues of running this in webpack. Most likely I want to use hotreloader.

Hope you have any solutions for me.

Grtz

Willem

**Comment by gnuton** [comment]
My PR should fix this issue.

**Comment by edelinpetrov** [comment]
I would love to see that PR merged.

**Comment by rameden** [comment]
Same here!

**Comment by jackreichert** [comment]
@gnuton I've implemented some of the ideas in the pull request, but there were conflicts so I closed it. If you'd like to submit again, please feel free to. 

@gluharche Please let me know what issues you are having, I'd be happy to help you sort it out.

**Comment by gnuton** [comment]
@jackreichert no problems.
