### ISSUE TITLE
Some questions about variables

### ISSUE THREAD

**Issue by TimurGumarov** [jackreichert/a-wp-react-redux-theme#4]
Hi @jackreichert !
Thank you for this project, great job!

Had some questions about `${RT_API}` variable. What is it and where it gets it's values? I found this variable but not found declaration of it.

**Comment by jackreichert** [comment]
Hi Tim, 

Thanks for your nice words!

The variable is defined here: https://github.com/jackreichert/a-wp-react-redux-theme/blob/master/lib/theme-enqueue.php#L24

Please share what you do with the theme. I'd love to see it!

**Comment by TimurGumarov** [comment]
Yeah, thank you for response, @jackreichert !
My brains exploaded when I tryed to find declaration of this variable.))

I do my own project founded on different ideas including your theme.
Follow me, I'll shere it soon.

**Comment by jackreichert** [comment]
Yep, if you weren't familiar with localize_script() it would be very hard to find.
