### ISSUE TITLE
Some questions about creating wp react themes

### ISSUE THREAD

**Issue by zhboner** [jackreichert/a-wp-react-redux-theme#5]
Hi,
Currently I am doing my own theme so come to your project. Thank you for your wonderful work that gives me a good example. I am wondering some things: 
- How can you get blog address on react side. (I think this is necessary to use RESTful API)
- How can you make react router work with wordpress so any static files can be fetched from server
-  I notices you used a variable RT_API but I can't find its definition. Can you give me some help?
Thank you.

**Comment by veysiyildiz** [comment]
you can find RT_API in /lib/theme-enqueue.php:20

**Comment by zhboner** [comment]
I see.
Thank you.

**Comment by jackreichert** [comment]
Thanks @veysiyildiz for your helpful comment!
