### ISSUE TITLE
This is sick!!!

### ISSUE THREAD

**Issue by coolcourd** [jackreichert/a-wp-react-redux-theme#6]
one recommendation is figuring out how to make this link internal links correctly to not reload the page. so if i create a page and have a button or a <a> tag that links to another page it currently does a new http request when it doesn't need to. i tried using a react router Link tag as well and that diddnt work. it would be sweet if you found a way to make this check if a link is internal and if so use client side routing like it does in the menu.

**Comment by jackreichert** [comment]
@coolcourd I've implemented this in the latest version. Please let me know how it works for you. The solution I came up with is here: https://github.com/jackreichert/a-wp-react-redux-theme/blob/master/src/containers/parts/content.js#L10

**Comment by coolcourd** [comment]
Awesome! I will definitely check it out again. This project has inspired me. I am glad you are still improving it. This could be the new wordpress standard. Ur a pioneer. Keep it up

**Comment by jackreichert** [comment]
It's an honor, thank you for your kind words!
