### ISSUE TITLE
Loaded theme and demo content but nothing showing

### ISSUE THREAD

**Issue by dirtandrust** [jackreichert/a-wp-react-redux-theme#9]
Hi, loving the theme so far and it's a great place to start! Docs say it works out of the box but it's not showing content, only empty boxes, is there something I missed in the set up process? See screenshot to see what I'm seeing.

Using: 
- MAMP on a Mac running 10.11.5, developing locally
- debug set to true, no errors or warnings
- wp 4.9.2
- Sublime Text 2 editor
- Bulk Content Creator wp plugin
- WP Example Content wp plugin
 
![screen shot 2018-01-25 at 12 43 48 pm](https://user-images.githubusercontent.com/1700664/35386756-7959a4de-01cd-11e8-9239-2a21faf7acbd.jpg)

Note: It does load at http://localhost:8888/ without the directory in the url, but obviously I can't have it work this way because I have other sites to work on (my htaccess is set to default to the directory which in my case is http://localhost:8888/reactwpapi)

**Comment by jackreichert** [comment]
Hmm, I just tested it with a fresh install + MAMP, and am not able to reproduce. 

That means I need more info from you...

Do you have any errors in the console?

**Comment by dirtandrust** [comment]
Hi yes here’s the error I get when I run webpack in the theme: 

nathanielflick@dirtandrust /Applications/MAMP/htdocs/reactwpapi/wp-content/themes/a-wp-react-redux-theme-master (master) $ webpack
/Applications/MAMP/htdocs/reactwpapi/node_modules/extract-text-webpack-plugin/index.js:114
		throw new Error("Breaking change: ExtractTextPlugin now only takes a single argument. Either an options " +
		^

Error: Breaking change: ExtractTextPlugin now only takes a single argument. Either an options object *or* the name of the result file.
Example: if your old code looked like this:
    new ExtractTextPlugin('css/[name].css', { disable: false, allChunks: true })

You would change it to:
    new ExtractTextPlugin({ filename: 'css/[name].css', disable: false, allChunks: true })

The available options are:
    filename: string
    allChunks: boolean
    disable: boolean

    at new ExtractTextPlugin (/Applications/MAMP/htdocs/reactwpapi/node_modules/extract-text-webpack-plugin/index.js:114:9)
    at Object.<anonymous> (/Applications/MAMP/htdocs/reactwpapi/wp-content/themes/a-wp-react-redux-theme-master/webpack.config.js:47:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at requireConfig (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:96:18)
    at /usr/local/lib/node_modules/webpack/bin/convert-argv.js:109:17

Cheers
----
Nathaniel Flick
Dirt and Rust, Limited (NZ)
nat@dirtandrust.com
dirtandrust.com
Skype: nathaniel.flick

**Comment by jackreichert** [comment]
Thanks Nathaniel,

That was very helpful. I changed the offending line [here](https://github.com/jackreichert/a-wp-react-redux-theme/blob/master/webpack.config.js#L47)

Let me know if you continue to have issues.

**Comment by dirtandrust** [comment]
This is awesome, thank you!

Are you able to fix the home logo url so it works on any domain, rather than pointing to "/"?
